force-app/main/default/objects/Contact/fields/Monthly_Income__c.field-meta.xml
<CustomField>
    <fullName>Monthly_Income__c</fullName>
    <label>Monthly Income</label>
    <precision>18</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Support_Option__c.field-meta.xml
<CustomField>
    <fullName>Support_Option__c</fullName>
    <label>Support Option</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Option 1</fullName>
            </value>
            <value>
                <fullName>Option 2</fullName>
            </value>
            <value>
                <fullName>Option 3</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/DM_Contact.cls
public with sharing class DM_Contact {
     public static Contact getContactByPhone( String phone ) {
        List<Contact> contacts = [
            SELECT Id,
                   FirstName,
                   LastName,
                   Phone,
                   MailingPostalCode,
                   Monthly_Income__c,
                   Support_Option__c
            FROM Contact
            WHERE Phone = :phone
            LIMIT 1
        ];

        return contacts.isEmpty() ? null : contacts[0];
    }
}